GNU nano 6.2                                                                                                                                                                                             homework8.yml
---
- name: Install Tomcat9
  hosts: web
  become: yes
  tasks:
    - name: update
      apt: update_cache=yes
      ignore_errors: yes
    - name: Installation JDK
      apt:
        name: default-jdk
        state: latest

    #    - name: add tomcat group
    #      group:
    #        name: tomcat
    #    - name: add tomcat user
    #      user:
    #          name: tomcat
    #          group: tomcat
    #          home: /user/share/tomcat
    #          createhome: no

    - name: download & unarchive
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [ --strip-components=1 ]

    - name: create /opt/tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755

    - name: Extracting Apache Tomcat.
      shell: tar -xzvf /tmp/apache-tomcat-9*tar.gz -C /opt/tomcat --strip-components=1

    - name: Change ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    #    - name: Copy Tomcat service from local to remote
    #      copy:
    #          src: tomcat.service
    #          dest: /etc/systemd/system/
    #          mode: 0755

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: true



- name: Building project
  hosts: db
  become: yes

  tasks:
    - name: Ensure maven package is present
      apt:
        name: maven
        state: latest
    - name: Ensure git package is present
      apt:
        name: git
        state: latest
    - name: Ensure default-jdk package is present
      apt:
        name: default-jdk
        state: latest

    - name: Clone a github repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /home/ubuntu/boxfuse
        clone: yes
        update: yes

    - name: Extracting Apache Tomcat.
      args:
        chdir: /home/ubuntu/boxfuse/
      shell: mvn package

    - name: Synchronization of src on the inventory host to>
      synchronize:
        src: /home/ubuntu/boxfuse/target/hello-1.0.war
        dest: /opt/tomcat/webapps/
        mode: pull
      delegate_to: 3.124.192.16


