
---
- name: Install Tomcat9
  hosts: web
  become: yes
  tasks:
    - name: update
      apt: update_cache=yes
      ignore_errors: yes
    - name: Installation JDK.
      apt:
        name: default-jdk
        state: latest
   # - name: Installation curl.
   #   apt:
   #     name: curl
   #     state: latest

   # - name: Installation wget.
   #   apt:
   #     name: wget
   #     state: latest

   # - name: Adding Group and user for Tomcat.
   #   shell: groupadd tomcat && useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
    - name: add tomcat group
      group:
        name: tomcat
    - name: add tomcat user
      user:
          name: tomcat
          group: tomcat
          home: /user/share/tomcat
          createhome: no
    #- name: Downloading Apache Tomcat tar.
    #  shell: wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
    #  args:
    #    chdir: /tmp
    - name: download & unarchive
      unarchive:
          src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
          dest: /opt/tomcat
          remote_src: yes
          extra_opts: [ --strip-components=1 ]
    #- name: Creating Apache Tomcat home directory.
    #  command: mkdir /opt/tomcat
    - name: create /opt/tomcat directory
      file:
          path: /opt/tomcat
          state: directory
          mode: 0755

    - name: Extracting Apache Tomcat.
      shell: tar -xzvf /tmp/apache-tomcat-9*tar.gz -C /opt/tomcat --strip-components=1
    #- name: Updating permission.
    # command: "{{ item }}"
    #  with_items:
    #      - chown -R tomcat:tomcat /opt/tomcat
    #      - chmod -R g+r /opt/tomcat/conf
    #      - chmod g+x /opt/tomcat/conf
    - name: Change ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
    #- name: Creating service for Apache tomcat.
    #  file:
    #    path: /etc/systemd/system/tomcat.service
    #   state: touch
    #   mode: u+rwx,g-rwx,o-x
    - name: Copy Tomcat service from local to remote
      copy:
          src: tomcat.service
          dest: /etc/systemd/system/
          mode: 0755
    #- name: download foo.conf
    #  get_url:
    #    url: https://raw.githubusercontent.com/aftab70/Apache_Tomcat/master/tomcat_services
    #    dest: /etc/systemd/system/tomcat.service

    #- name: Deamon reload.
    #  command: systemctl daemon-reload

    #- name: Starting Apache Tomcat service.
    #  service: name=tomcat state=started
    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: true



- name: Building project
  hosts: db
  become: yes

  tasks:
    - name: Ensure maven package is present
      apt:
        name: maven
        state: latest
    - name: Ensure git package is present
      apt:
        name: git
        state: latest
    - name: Ensure git package is present
      apt:
        name: default-jdk
        state: latest

    - name: Ensure git package is present
      apt:
        name: wget
        state: latest

    - name: Clone a github repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /home/ubuntu/boxfuse
        clone: yes
        update: yes

    - name: Extracting Apache Tomcat.
      args:
        chdir: /home/ubuntu/boxfuse/
      shell: mvn package



- name: Building project
  hosts: db
  become: yes

  #tasks:
   # - name: test sync
   #   synchronize:
   #     mode: pull
   #     src: '/home/ubuntu/boxfuse/hello-1.0.war'
   #     dest: '/opt/tomcat/webapps/'
   #   delegate_to: web

- name: Moving project
  hosts: db
  tasks:
    - name:
      apt:
        name: rsync
        state: present
        become: yes

    - name: Synchronization of src on the control machine to dest on the remote hosts
      ansible.posix.synchronize:
        src: /home/ubuntu/boxfuse/hello-1.0.war
        dest: /opt/tomcat/webapps/






