---
- name: Install nginx
  hosts: all
  become: yes
  vars:
    source_folder: ./
    dest_folder: /var/www/html
  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present
    - name: Templating index.html
      template: src={{source_folder}}/index.j2 dest={{dest_folder}}/index.html mode=0555

  handlers:
    - name: restart nginx
      service: name=nginx state=present