---
- name: Install nginx
  hosts: web
  become: yes

  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present
    - name: Delete file
      lineinfile:
        path: /var/www/html/index.html
        regex: "Welcome to NGINX"
        line: <p><script> document.write(new Date().toLocaleDateString()); </script></p>